---
- hosts: k3s_cluster
  become: yes
  vars_files: inventory/group_vars/secret.yml
  vars:
    ansible_sudo_pass: "{{ pass }}"
  roles:
    - container_features
    - dphys_swapfile

- hosts: localhost
  roles:
    - bootstrap_k3sup
    - k3s_cluster

- hosts: k3s_cluster
  become: yes
  vars_files: inventory/group_vars/secret.yml
  vars:
    ansible_sudo_pass: "{{ pass }}"
  roles:
    - undosudo