---

- name: Install kube-vip as network LoadBalancer - Install the kube-vip Cloud Provider
  command:
    cmd: kubectl apply -f https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/main/manifest/kube-vip-cloud-controller.yaml

- name: Install Metallb
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/namespace.yaml
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.12/config/manifests/metallb-native.yaml

- name: LB Range
  template:
    src: "lbrange.yaml.j2"
    dest: /home/{{ lookup('env','USER') }}/ipAddressPool.yaml
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
    mode: 0644

- name: Deploy IP Pools and l2Advertisement
  shell: |
    kubectl wait --namespace metallb-system \
                    --for=condition=ready pod \
                    --selector=component=controller \
                    --timeout=120s
    kubectl apply -f /home/{{ lookup('env','USER') }}/ipAddressPool.yaml
    kubectl apply -f https://raw.githubusercontent.com/JamesTurland/JimsGarage/main/Kubernetes/K3S-Deploy/l2Advertisement.yaml

    kubectl get nodes
    kubectl get svc
    kubectl get pods --all-namespaces -o wide
  register: kubestatus
  tags: status

- name: kubestatus
  debug: var=kubestatus
  tags: status

- name: Deploy NGINX
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/inlets/inlets-operator/master/contrib/nginx-sample-deployment.yaml -n default
    kubectl expose deployment nginx-1 --port=80 --type=LoadBalancer -n default
  register: nginx
  ignore_errors: yes
  tags: status

- name: nginx
  debug: var=nginx
  tags: status