---

- name: Copy Longhorn.yml
  template:
    src: "longhorn.yaml.j2"
    dest: /home/{{ lookup('env','USER') }}/longhorn.yaml
  tags:
  - longhorn
  - never

- name: Deploy Longhorn
  shell: |
    kubectl apply -f /home/{{ lookup('env','USER') }}/longhorn.yaml
    kubectl get pods --namespace longhorn-system
  register: longhorn
  ignore_errors: yes
  tags:
  - longhorn
  - never

- name: Longhorn
  debug: var=longhorn
  tags:
  - longhorn
  - never

- name: Deploy Longhorn Status
  shell: |
    kubectl get pods --namespace longhorn-system --watch
    kubectl get nodes
    kubectl get svc -n longhorn-system
  register: longhornstatus
  ignore_errors: yes
  tags:
  - longhorn
  - never

- name: LonghornStatus
  debug: var=longhornstatus
  tags:
  - longhorn
  - never
