---

- name: Install Kuve-VIP for HA
  command:
    cmd: kubectl apply -f https://kube-vip.io/manifests/rbac.yaml

# - name: Download vip rbac manifest to first master
#   ansible.builtin.get_url:
#     url: "https://raw.githubusercontent.com/kube-vip/kube-vip/{{ kube_vip_tag_version }}/docs/manifests/rbac.yaml"
#     dest: "/tmp/vip-rbac.yaml"
#     owner: root
#     group: root
#     mode: 0644
# 

- name: Create manifests directory on first master
  become: yes
  file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: 0644
  delegate_to: debianvmk1

- name: Copy vip manifest to first master
  become: yes
  template:
    src: "vip.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/kube-vip.yaml"
    owner: root
    group: root
    mode: 0644
  delegate_to: debianvmk1
