---

- name: Install Kuve-VIP for HA
  command:
    cmd: kubectl apply -f https://kube-vip.io/manifests/rbac.yaml

- name: Create manifests directory on first master
  become: yes
  file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: 0644
  delegate_to: "{{item}}"
  with_items: "{{ groups['master'][0] }}"

- name: Copy vip manifest to first master
  become: yes
  template:
    src: "vip.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/kube-vip.yaml"
    owner: root
    group: root
    mode: 0644
  delegate_to: "{{item}}"
  with_items: "{{ groups['master'][0] }}"
